/*
 * SonarQube
 * Copyright (C) 2009-2017 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.sonar.db.measure;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import javax.annotation.CheckForNull;
import javax.annotation.Nullable;

public class LiveMeasureDto {

  private static final int MAX_TEXT_VALUE_LENGTH = 4000;

  private String uuid;
  private String componentUuid;
  private String projectUuid;
  private int metricId;
  @Nullable
  private Double value;
  @Nullable
  private String textValue;
  @Nullable
  private byte[] data;
  @Nullable
  private Double variation;

  public String getUuid() {
    return uuid;
  }

  // method is not public because UUID is generated by dao only
  void setUuid(String s) {
    this.uuid = s;
  }

  public String getComponentUuid() {
    return componentUuid;
  }

  public void setComponentUuid(String s) {
    this.componentUuid = s;
  }

  public String getProjectUuid() {
    return projectUuid;
  }

  public void setProjectUuid(String s) {
    this.projectUuid = s;
  }

  public int getMetricId() {
    return metricId;
  }

  public void setMetricId(int i) {
    this.metricId = i;
  }

  @CheckForNull
  public Double getValue() {
    return value;
  }

  public void setValue(@Nullable Double value) {
    this.value = value;
  }

  @CheckForNull
  public String getTextValue() {
    return textValue;
  }

  @CheckForNull
  public byte[] getData() {
    return data;
  }

  @CheckForNull
  public String getDataAsString() {
    if (data != null) {
      return new String(data, StandardCharsets.UTF_8);
    }
    return textValue;
  }

  public void setData(@Nullable String data) {
    if (data == null) {
      this.textValue = null;
      this.data = null;
    } else if (data.length() > MAX_TEXT_VALUE_LENGTH) {
      this.textValue = null;
      this.data = data.getBytes(StandardCharsets.UTF_8);
    } else {
      this.textValue = data;
      this.data = null;
    }
  }

  public void setData(@Nullable byte[] data) {
    this.textValue = null;
    this.data = data;
  }

  @CheckForNull
  public Double getVariation() {
    return variation;
  }

  public void setVariation(@Nullable Double variation) {
    this.variation = variation;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LiveMeasureDto{");
    sb.append("uuid='").append(uuid).append('\'');
    sb.append(", componentUuid='").append(componentUuid).append('\'');
    sb.append(", projectUuid='").append(projectUuid).append('\'');
    sb.append(", metricId=").append(metricId);
    sb.append(", value=").append(value);
    sb.append(", textValue='").append(textValue).append('\'');
    sb.append(", data=").append(Arrays.toString(data));
    sb.append(", variation=").append(variation);
    sb.append('}');
    return sb.toString();
  }
}
